env:
  TERM: "xterm-256color"

window:
  dimensions:
    columns: 70
    lines: 47
  position:
    x: 10
    y: 10

    padding:
      x: 0
      y: 0

    dynamic_padding: false

  decorations: full

  startup_mode: Windowed

  # Window title
  title: Alacritty

  dynamic_title: true

scrolling:
  # Specifying '0' will disable scrolling.
  history: 10000

  # Scrolling distance multiplier.
  multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Default:
    #   - (Linux/BSD) monospace
    family: DroidSansMono Nerd Font
    style: Book
    size: 20

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

# Background opacity
background_opacity: 0.8

cursor:
  # Cursor style
  style: Block

  # Cursor blinking state
  blinking: Always

  # Cursor blinking interval in milliseconds.
  blink_interval: 750

  # window is not focused.
  unfocused_hollow: true

mouse:
  hide_when_typing: true
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

live_config_reload: true
selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: false

# Shell
shell:
  program: /usr/bin/zsh

key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: F11, mods: None, action: ToggleFullscreen }
  - { key: Paste, mods: None, action: Paste }
  - { key: Copy, mods: None, action: Copy }
  - { key: L, mods: Control, action: ClearLogNotice }
  - { key: L, mods: Control, chars: "\x0c" }
  - { key: PageUp, mods: None, action: ScrollPageUp, mode: ~Alt }
  - { key: PageDown, mods: None, action: ScrollPageDown, mode: ~Alt }
  - { key: Home, mods: Shift, action: ScrollToTop, mode: ~Alt }
  - { key: End, mods: Shift, action: ScrollToBottom, mode: ~Alt }

schemes:
  ### Doom One ###
  doom-one: &doom-one
    primary:
      background: "#282c34"
      foreground: "#bbc2cf"
    cursor:
      text: CellBackground
      cursor: "#528bff"
    selection:
      text: CellForeground
      background: "#3e4451"
    normal:
      black: "#1c1f24"
      red: "#ff6c6b"
      green: "#98be65"
      yellow: "#da8548"
      blue: "#51afef"
      magenta: "#c678dd"
      cyan: "#5699af"
      white: "#202328"
    bright:
      black: "#5b6268"
      red: "#da8548"
      green: "#4db5bd"
      yellow: "#ecbe7b"
      blue: "#3071db" # This is 2257a0 in Doom Emacs but I lightened it.
      magenta: "#a9a1e1"
      cyan: "#46d9ff"
      white: "#dfdfdf"

  ### Dracula ###
  dracula: &dracula
    primary:
      background: "#282a36"
      foreground: "#f8f8f2"
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: "#44475a"
        background: "#50fa7b"
      focused_match:
        foreground: "#44475a"
        background: "#ffb86c"
      bar:
        background: "#282a36"
        foreground: "#f8f8f2"
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: "#44475a"
    normal:
      black: "#000000"
      red: "#ff5555"
      green: "#50fa7b"
      yellow: "#f1fa8c"
      blue: "#bd93f9"
      magenta: "#ff79c6"
      cyan: "#8be9fd"
      white: "#bfbfbf"
    bright:
      black: "#4d4d4d"
      red: "#ff6e67"
      green: "#5af78e"
      yellow: "#f4f99d"
      blue: "#caa9fa"
      magenta: "#ff92d0"
      cyan: "#9aedfe"
      white: "#e6e6e6"
    dim:
      black: "#14151b"
      red: "#ff2222"
      green: "#1ef956"
      yellow: "#ebf85b"
      blue: "#4d5b86"
      magenta: "#ff46b0"
      cyan: "#59dffc"
      white: "#e6e6d1"

  ### Gruvbox dark ###
  gruvbox-dark: &gruvbox-dark # Default colors
    primary:
      # hard contrast: background = '0x1d2021'
      background: "0x282828"
      # soft contrast: background = '0x32302f'
      foreground: "0xebdbb2"

    # Normal colors
    normal:
      black: "0x282828"
      red: "0xcc241d"
      green: "0x98971a"
      yellow: "0xd79921"
      blue: "0x458588"
      magenta: "0xb16286"
      cyan: "0x689d6a"
      white: "0xa89984"

    # Bright colors
    bright:
      black: "0x928374"
      red: "0xfb4934"
      green: "0xb8bb26"
      yellow: "0xfabd2f"
      blue: "0x83a598"
      magenta: "0xd3869b"
      cyan: "0x8ec07c"
      white: "0xebdbb2"

  ### Nord ###
  nord: &nord # Default colors
    primary:
      background: "0x2E3440"
      foreground: "0xD8DEE9"

    # Normal colors
    normal:
      black: "0x3B4252"
      red: "0xBF616A"
      green: "0xA3BE8C"
      yellow: "0xEBCB8B"
      blue: "0x81A1C1"
      magenta: "0xB48EAD"
      cyan: "0x88C0D0"
      white: "0xE5E9F0"

    # Bright colors
    bright:
      black: "0x4C566A"
      red: "0xBF616A"
      green: "0xA3BE8C"
      yellow: "0xEBCB8B"
      blue: "0x81A1C1"
      magenta: "0xB48EAD"
      cyan: "0x8FBCBB"
      white: "0xECEFF4"

  ### Solarized Light ###
  solarized-light: &solarized-light # Default colors
    primary:
      background: "#fdf6e3" # base3
      foreground: "#657b83" # base00

    # Cursor colors
    cursor:
      text: "#fdf6e3" # base3
      cursor: "#657b83" # base00

    # Normal colors
    normal:
      black: "#073642" # base02
      red: "#dc322f" # red
      green: "#859900" # green
      yellow: "#b58900" # yellow
      blue: "#268bd2" # blue
      magenta: "#d33682" # magenta
      cyan: "#2aa198" # cyan
      white: "#eee8d5" # base2

    # Bright colors
    bright:
      black: "#002b36" # base03
      red: "#cb4b16" # orange
      green: "#586e75" # base01
      yellow: "#657b83" # base00
      blue: "#839496" # base0
      magenta: "#6c71c4" # violet
      cyan: "#93a1a1" # base1
      white: "#fdf6e3" # base3

  ### Solarized Dark ###
  solarized-dark: &solarized-dark # Default colors
    primary:
      background: "#002b36" # base03
      foreground: "#839496" # base0

    # Cursor colors
    cursor:
      text: "#002b36" # base03
      cursor: "#839496" # base0

    # Normal colors
    normal:
      black: "#073642" # base02
      red: "#dc322f" # red
      green: "#859900" # green
      yellow: "#b58900" # yellow
      blue: "#268bd2" # blue
      magenta: "#d33682" # magenta
      cyan: "#2aa198" # cyan
      white: "#eee8d5" # base2

    # Bright colors
    bright:
      black: "#002b36" # base03
      red: "#cb4b16" # orange
      green: "#586e75" # base01
      yellow: "#657b83" # base00
      blue: "#839496" # base0
      magenta: "#6c71c4" # violet
      cyan: "#93a1a1" # base1
      white: "#fdf6e3" # base3

  ### Tomorrow Night ###
  tomorrow-night: &tomorrow-night # Default colors
    primary:
      background: "0x1d1f21"
      foreground: "0xc5c8c6"

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: "0x1d1f21"
      cursor: "0xffffff"

    # Normal colors
    normal:
      black: "0x1d1f21"
      red: "0xcc6666"
      green: "0xb5bd68"
      yellow: "0xe6c547"
      blue: "0x81a2be"
      magenta: "0xb294bb"
      cyan: "0x70c0ba"
      white: "0x373b41"

    # Bright colors
    bright:
      black: "0x666666"
      red: "0xff3334"
      green: "0x9ec400"
      yellow: "0xf0c674"
      blue: "0x81a2be"
      magenta: "0xb77ee0"
      cyan: "0x54ced6"
      white: "0x282a2e"

######################################################################
## SET THEME: Choose ONE color scheme from those in the above list. ##
## ###################################################################
# Available themes are:
# *doom-one
# *dracula
# *gruvbox-dark
# *nord
# *solarized-light
# *solarized-dark
# *tomorrow-night
colors: *dracula
